CREATE TABLE PRODUCT (
    PRO_ID      TEXT PRIMARY KEY,
    PRO_NAME    TEXT NOT NULL,
    PRO_PRICE   INTEGER NOT NULL,
    PRO_COM     TEXT NOT NULL
);

-- Insert sample computer store products
INSERT INTO PRODUCT (PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM)
VALUES
('101', 'MOTHER BOARD', 3200, 'TECHPRO'),
('102', 'KEY BOARD', 450, 'KEYMAX'),
('103', 'ZIP DRIVE', 250, 'DATAFIX'),
('104', 'SPEAKER', 550, 'SOUNDCO'),
('105', 'MONITOR', 5000, 'VIETTECH'),
('106', 'DVD DRIVE', 900, 'DATAFIX'),
('107', 'CD DRIVE', 800, 'DATAFIX'),
('108', 'PRINTER', 2600, 'PRINTPLUS'),
('109', 'REFILL CARTRIDGE', 350, 'PRINTPLUS'),
('110', 'MOUSE', 250, 'KEYMAX');


SELECT * FROM PRODUCT
WHERE PRO_PRICE  < 1000 AND PRO_COM = 'PRINTPLUS' ;

SELECT * FROM PRODUCT
WHERE PRO_COM = 'PRINTPLUS' OR PRO_PRICE < 500

SELECT * FROM PRODUCT
WHERE PRO_COM = 'DATAFIX' AND(PRO_PRICE  < 1000 OR PRO_PRICE  < 2000)

SELECT * FROM PRODUCT
WHERE PRO_NAME  LIKE 'M%';

SELECT * FROM PRODUCT
WHERE PRO_NAME  LIKE '%DRIVE';

SELECT PRO_NAME, PRO_PRICE FROM PRODUCT
WHERE PRO_PRICE = ( SELECT MIN(PRO_PRICE) FROM PRODUCT
);


SELECT PRO_NAME, PRO_PRICE FROM PRODUCT
WHERE PRO_PRICE = ( SELECT MAX(PRO_PRICE) FROM PRODUCT


UPDATE PRODUCT
SET PRO_PRICE = 600
WHERE PRO_ID = 104

SELECT * FROM PRODUCT
WHERE PRO_ID = 104;

DELETE FROM PRODUCT
WHERE PRO_ID = 103;

SELECT * FROM PRODUCT